package frc.robot;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class Constants {
        public static final double stickDeadband = 0.1;

    //Motor CAN IDs
    public static final int LeftClimb = 7;
    public static final int RightClimb = 2;
    public static final int LeftShooter = 5;
    public static final int RightShooter = 6;
    public static final int LeftArm = 3;
    public static final int RightArm = 10;
    public static final int Intake = 8;


    public static final double armPower = 0.2;
  
    //Sensor CAN IDs
    public static final int armEncoder = 100;

    //auto constants
    public static final double autoShootingVelocity = 2;

    //Arm Positions
    public static final double armFloorPosition = 0;


}