package frc.robot;

import java.io.File;
import java.nio.file.Path;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.wpilibj.Filesystem;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class Constants {
        public static final double stickDeadband = 0.1;

    //Motor CAN IDs
    public static final int LeftClimb = 7;
    public static final int RightClimb = 2;
    public static final int LeftShooter = 5;
    public static final int RightShooter = 6;
    public static final int LeftArm = 3;
    public static final int RightArm = 10;
    public static final int Intake = 8;


    public static final double armPower = 0.6;
  
    //Sensor CAN IDs
    public static final int armEncoder = 100;

    //auto constants
    public static final double autoShootingVelocity = 2;

    //Arm Positions
    public static final double armFloorPosition = 0;

    public static final class SwerveConstants {
        public static final double MaxSpeed = 6;
        public static final double MaxAngularSpeed = 4 * Math.PI;
    }

    public static final class PoseConstants {
        public static final Pose2d defaultPose = new Pose2d(new Translation2d(0,0), Rotation2d.fromDegrees(0));
        public static final Pose2d Blue1Pose = new Pose2d(new Translation2d(2,7), Rotation2d.fromDegrees(0));
        public static final Pose2d Blue2Pose = new Pose2d(new Translation2d(2,5), Rotation2d.fromDegrees(0));
        public static final Pose2d Blue3Pose = new Pose2d(new Translation2d(2,2), Rotation2d.fromDegrees(0));

    }
        public static final class Aiming 
    {
        public static final double Home = -1.25;
        public static final double Amp = 13.3;
        public static final double Source = 16.7;
        public static final double Position = 4.5;
        public static final double Farback = 7.25;
    }
  public static final Path APRILTAG_FIELD_LAYOUT_PATH =
      new File(Filesystem.getDeployDirectory(), "2024-crescendo.json").toPath();
      
      public static class OperatorConstants
      {public static final int kDriverControllerPort = 0;
    
        // Joystick Deadband
        public static final double LEFT_X_DEADBAND  = 0.1;
        public static final double LEFT_Y_DEADBAND  = 0.1;
        public static final double RIGHT_X_DEADBAND = 0.1;
        public static final double TURN_CONSTANT    = 6;
      }
      public static class Arm{

        public static final double ArmUpSpeed = 1.0;
        public static final double ArmDownSpeed = -1.0;
      
        public static final double MAX_CURRENT_DRAW = 25;
      
      public static final double Shooting_SetPoint1 = 0 ;
      public static final double Shooting_SetPoint2 = 0 ;
      public static final double FloorPickup_SetPoint = 0 ;
      
      // public static final double RawAngleHex_To_EncoderConversion_Rate = 0 ;
      
      
      }



}